### ISSUE TITLE
 Error: Got unexpected extra argument (gibbs)

### ISSUE THREAD

**Issue by zhangbenbenchina** [caporaso-lab/sourcetracker2#157]
Follow the installation tutorial. After installation, you can find sourcetracker2 gibbs --help  but cannot use the command；

(st2)h @happydeMacBook-Pro sourcetracker2 % ls
example1	map.txt		otu_table.biom	otu_table.txt
(st2) h@happydeMacBook-Pro sourcetracker2 % sourcetracker2 gibbs -i otu_table.biom -m map.txt -o example1/

Usage: sourcetracker2 [OPTIONS]
Try 'sourcetracker2 --help' for help.

Error: Got unexpected extra argument (gibbs)

**Comment by cherman2** [comment]
Hi @zhangbenbenchina, 
Thank you for bringing this issue up. This will be fixed once #159 is merged. This should be fixed by end of week! I will update again once this is fixed
